# Generated by Django 3.1.6 on 2021-02-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='instruction_video',
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
