# Generated by Django 3.1.6 on 2021-03-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_flow_subflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
