# Generated by Django 3.1.6 on 2021-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('exercise', '0010_auto_20210326_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.Equipment'),
        ),
    ]
