# Generated by Django 3.1.6 on 2021-02-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name of exercise')),
                ('description', models.TextField(verbose_name='Description of exercise')),
                ('instruction_video', models.URLField(max_length=500)),
                ('silent', models.BooleanField(default=False)),
                ('equipment', models.BooleanField(default=False)),
            ],
        ),
    ]
