# Generated by Django 3.1.6 on 2021-02-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20210214_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Stretch', 'Stretch')], max_length=100),
        ),
    ]
